apiVersion: v1
kind: PersistentVolume
metadata:
  name: embeddings-server-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /workspaces/embeddings-storage
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: embeddings-server-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: embeddings-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embeddings-server
  template:
    metadata:
      labels:
        app: embeddings-server
    spec:
      volumes:
        - name: embeddings-server-v
          persistentVolumeClaim:
            claimName: embeddings-server-volume-claim
      containers:
        - name: embeddings-server
          image: robertmmarek/embeddings-server:latest
          ports:
            - containerPort: 6333
          volumeMounts:
            - mountPath: "/embeddings/storage"
              name: embeddings-server-v
          env:
            - name: QDRANT_SERVER_HOSTNAME
              value: 'qdrant-server-service.default.cluster.local'
            - name: QDRANT_SERVER_PORT
              value: '6333'
---
apiVersion: v1
kind: Service
metadata:
  name: embeddings-server-service
spec:
  selector:
    app: embeddings-server
  ports:
    - protocol: TCP
      port: 6433
      targetPort: 6433
  type: LoadBalancer
