apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrant-server-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /workspaces/qdrant-storage
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-server-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant-server
  template:
    metadata:
      labels:
        app: qdrant-server
    spec:
      volumes:
        - name: qdrant-server-v
          persistentVolumeClaim:
            claimName: qdrant-server-volume-claim
      containers:
        - name: qdrant-server
          image: qdrant/qdrant:v1.5.0
          ports:
            - containerPort: 6333
          volumeMounts:
            - mountPath: "/qdrant/storage"
              name: qdrant-server-v
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-server-service
spec:
  selector:
    app: qdrant-server
  ports:
    - protocol: TCP
      port: 6333
      targetPort: 6333
  type: LoadBalancer
